### ISSUE TITLE
Cannot use it.

### ISSUE THREAD

**Issue by Ayfri** [bevry/make-deno-edition#89]
I tried everything, but every single time, it sends me a "path" error.

```js
❯ make-deno-edition --attempt
make-deno-edition: UNEXEPCTED FAILURE!

Unable to make the deno edition, due to this unexpected error:
Error: Illegal characters in path.
    at pathArg (C:\Users\Pierre\AppData\Roaming\npm\node_modules\make-deno-edition\node_modules\mkdirp\lib\path-arg.js:20:27)
    at Object.mkdirp [as default] (C:\Users\Pierre\AppData\Roaming\npm\node_modules\make-deno-edition\node_modules\mkdirp\index.js:10:10)
    at ensureFile (C:\Users\Pierre\AppData\Roaming\npm\node_modules\make-deno-edition\edition-esnext\index.js:77:24)
    at Object.make (C:\Users\Pierre\AppData\Roaming\npm\node_modules\make-deno-edition\edition-esnext\index.js:456:11)
    at async bin (C:\Users\Pierre\AppData\Roaming\npm\node_modules\make-deno-edition\edition-esnext\bin.js:54:19) {
  path: 'C:\\Users\\Pierre\\WebstormProjects\\libs\\Advanced Command Handler\\source\\edition-deno\\C:\\Users\\Pierre\\WebstormProjects\\libs\\Advanced Command Handler\\source\\src',
  code: 'EINVAL'
}
```

```json
"editions": [
	  {
		    "description": "TypeScript source code with Import for modules",
		    "directory": "src",
		    "entry": "index.ts",
		    "tags": [
			    "src",
			    "typescript",
			    "import"
		    ],
		    "engines": false
	  },
	  {
		    "description": "TypeScript source code with Import for modules",
		    "directory": "edition-deno",
		    "entry": "index.ts",
		    "tags": [
			    "typescript",
			    "import",
			    "deno"
		    ],
		    "engines": {
			    "deno": "true",
			    "browsers": false
		    }
	  }
],
	```

**Comment by balupton** [comment]
Thanks for the report. Added to my todos. Not sure when I will get to it though, but have a batch of work for the next several weeks, which I hope to include this in.

**Comment by balupton** [comment]
Hoping to address this sometime this week.

**Comment by Ayfri** [comment]
Thanks x)

**Comment by balupton** [comment]
new version published, might fix the issues, let me know if not
